{
 "title": "Kubernetes Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Node number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(kube_node_created)" }
   ]
  },
  {
   "title": "apiserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"apiserver\"})"
    }
   ]
  },
  {
   "title": "scheduler",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-scheduler\"})"
    }
   ]
  },
  {
   "title": "etcd",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "kubelet",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"kubelet\"})"
    }
   ]
  },
  {
   "title": "controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\"})"
    }
   ]
  },
  {
   "title": "Coredns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{addonmanager_kubernetes_io_mode!=\"Reconcile\", job=\"coredns\"})"
    }
   ]
  },
  {
   "title": "PODs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_info{created_by_kind != \"Workflow\"})"
    }
   ]
  },
  {
   "title": "Pod 갯수 ",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc (count by (node) (kube_pod_info{created_by_kind != \"Workflow\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "노드 Liveness",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 3, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\", condition=\"Ready\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Kubernetes System Deployment Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "List of Deployment",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{exported_namespace=\"kube-system\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Desired pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{exported_namespace=\"kube-system\"})"
    }
   ]
  },
  {
   "title": "Current pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{exported_namespace=\"kube-system\"})"
    }
   ]
  },
  {
   "title": "Desired pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{exported_namespace=\"kube-system\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Current pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{exported_namespace=\"kube-system\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Available pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{exported_namespace=\"kube-system\"})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{exported_namespace=\"kube-system\"})"
    }
   ]
  },
  {
   "title": "Available pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{exported_namespace=\"kube-system\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Unavailable pods per deployment",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{exported_namespace=\"kube-system\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Kubernetes Cluster Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "title": "Sum CPU requests per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sum CPU allocatable per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sum Memory requests per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sum Memory allocatable per node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}