{
 "title": "Kubernetes Cluster Status",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "master_name", "query": ".+master.+" }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Server",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Up",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(up{job=\"apiserver\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    }
   ]
  },
  {
   "title": "Controller Manager",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(up{job=\"kube-controller-manager\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(up{job=\"kube-controller-manager\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(up{job=\"kube-controller-manager\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(up{job=\"kube-scheduler\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(up{job=\"kube-scheduler\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "crit": 2,
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(up{job=\"kube-scheduler\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Has Leader",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "max(etcd_server_is_leader)",
     "legendFormat": "Has Leader",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "crit": 1,
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(etcd_server_has_leader)",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 2
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Warning / Critical",
     "expr": "sum(up{job=\"kube-etcd\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  {
   "title": "CoreDNS",
   "type": "vonage-status-panel",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "All",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "count(up{addonmanager_kubernetes_io_mode!=\"Reconcile\", job=\"coredns\"})",
     "legendFormat": "All",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(up{addonmanager_kubernetes_io_mode!=\"Reconcile\", job=\"coredns\"})",
     "legendFormat": "Up",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Down",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sum(up{addonmanager_kubernetes_io_mode!=\"Reconcile\", job=\"coredns\"} == bool 0)",
     "legendFormat": "Down",
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 1
    }
   ]
  },
  { "title": "Cluster-wide Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Overall Total Load & Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Total Load" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system'})",
     "legendFormat": "Total Number of Cores"
    },
    { "expr": "sum(node_load5)", "legendFormat": "Total 5 Minutes Load" },
    {
     "expr": "avg(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) * 100",
     "legendFormat": "Total Average Usage"
    }
   ]
  },
  {
   "title": "Overall Total & Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Total Memory" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Total Used"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))*100",
     "legendFormat": "Total Average Usage"
    }
   ]
  },
  {
   "title": "Overall Total & Average Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "Total Disk Volume" }
   ],
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total Disk Volume"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{fstype=~\"xfs|ext.*\"})by(device,instance))",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "(sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_size_bytes{fstype=~\"xfs|ext.*\"})by(device,instance)))",
     "legendFormat": "Total Average Usage"
    }
   ]
  },
  {
   "title": "Overall Network Usage (TX)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device=~\"cali\\\\w*\"}[5m])) * 8",
     "legendFormat": "Network Usage"
    }
   ]
  },
  {
   "title": "Overall Network Usage (RX)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"cali\\\\w*\"}[5m])) * 8",
     "legendFormat": "Network Usage"
    }
   ]
  },
  { "title": "Cluster Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Node Readiness (1: Ready)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Master Nodes Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 22 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status!=\"true\", node=~\"$master_name\"})",
     "legendFormat": "NotReady"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status=\"true\", node=~\"$master_name\"})",
     "legendFormat": "DiskPressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\", node=~\"$master_name\"})",
     "legendFormat": "MemoryPressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", status=\"true\", node=~\"$master_name\"})",
     "legendFormat": "PIDPressure"
    }
   ]
  },
  {
   "title": "Worker Nodes Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 22 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status!=\"true\", node!~\"$master_name\"})",
     "legendFormat": "NotReady"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", status=\"true\", node!~\"$master_name\"})",
     "legendFormat": "DiskPressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\", node!~\"$master_name\"})",
     "legendFormat": "MemoryPressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", status=\"true\", node!~\"$master_name\"})",
     "legendFormat": "PIDPressure"
    }
   ]
  },
  {
   "title": "Cluster Resource Usage per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Sum CPU requests per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sum Memory requests per node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"memory\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "POD Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Total pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 48 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " count(count by (pod)(kube_pod_container_info))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total PODs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 3, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count by (pod)(kube_pod_container_info))",
     "legendFormat": "POD"
    }
   ]
  },
  {
   "title": "Waiting PODs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting PODs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 3, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "Terminated PODs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 62 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated PODs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 3, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
    }
   ]
  },
  { "title": "PV Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "PV Usage (%) ",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 22, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * 100 ",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}